name: Release

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
#  build:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          make build
#      - uses: actions/upload-artifact@v3
#        with:
#          name: release-${{  github.ref_name }}
#          path: |
#            release/*
#
#      - uses: softprops/action-gh-release@v1
#        if: ${{ startsWith(github.ref, 'refs/tags/') }}
#        with:
#          draft: false
#          files: |
#            release/*
#          prerelease: false
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#  build-macos:
#    runs-on: macos-12
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          make release/sim-macos
#      - uses: actions/upload-artifact@v3
#        with:
#          name: release-${{  github.ref_name }}
#          path: |
#            release/*
#
#      - uses: softprops/action-gh-release@v1
#        if: ${{ startsWith(github.ref, 'refs/tags/') }}
#        with:
#          draft: false
#          files: |
#            release/*
#          prerelease: false
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: |
          make release/sim-win
      - uses: actions/upload-artifact@v3
        with:
          name: release-${{  github.ref_name }}
          path: |
            release/*

      - uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          files: |
            release/*
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}